# Generated by Django 4.2.14 on 2024-07-23 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Título')),
                ('min_text', models.CharField(default='Não gostei', max_length=100, verbose_name='Texto mínimo')),
                ('max_text', models.CharField(default='Gostei muito', max_length=100, verbose_name='Texto máximo')),
            ],
            options={
                'verbose_name': 'Pergunta',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'verbose_name': 'Alternativa',
            },
        ),
    ]
