# Generated by Django 5.0.7 on 2024-07-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_field', models.CharField(default='Hello, world!', max_length=100, verbose_name='Sample field')),
            ],
            options={
                'verbose_name': 'Sample model',
                'verbose_name_plural': 'Sample models',
            },
        ),
    ]
